name: Feature Branch Workflow

on: 
  push:
    branches:
      - feature-*
  workflow_dispatch:

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: unittest 
        run: echo "Run unittest"
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: code coverage 
        run: echo "Run code coverage checking"
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: sonarcloud  
        run: echo "Run SonarCloud"
  vuln-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Code Vulnerability Scan  
        run: echo "Run trivy"
  quality-gate:
    runs-on: ubuntu-latest
    needs: ["unittest", "coverage", "sonarcloud", "vuln-scan"]
    steps:
      - name: Quality Gate 
        run: echo "Run Quality gate"
  build:
    runs-on: ubuntu-latest
    needs: ["quality-gate"]
    steps:
      - name: Build, Tag, Docker image
        run: echo "docker build"  

  