name: Release workflow

on: 
  release:
    types:
      - published
    branches:
      - main

jobs:
  retag:
    runs-on: ubuntu-latest
    name: Retag image
    steps:
      - run: echo ${{ github.sha }}
      - run: echo ${{ github.ref }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - run: echo ${{ steps.get_version.outputs.VERSION }}